# Generated by Django 4.0.5 on 2022-06-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
